apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-state-metrics-scrape
  namespace: cost-optimizer
data:
  additional-scrape-configs.yaml: |
    - job_name: 'kube-state-metrics'
      static_configs:
        - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']

