apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-pushgateway
  namespace: cost-optimizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      labels:
        app: pushgateway
    spec:
      containers:
      - name: pushgateway
        image: prom/pushgateway:latest
        ports:
        - containerPort: 9091

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-pushgateway
  namespace: cost-optimizer
spec:
  selector:
    app: pushgateway
  ports:
  - port: http
    targetPort: 9091
    protocol: TCP

